# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# If not inside a tmux session, start a new session or join one
if test -z "$TMUX" -a "$TERM" != "linux" -a "$EUID" != "0" -a ! -f .notmux; then
  #tput cup 0 0 # reset cursor
  if tmux list-sessions >/dev/null 2>/dev/null; then
    exec tmux attach
  else
    which tmux >/dev/null && exec tmux new-session
  fi
fi

# Detect OS (kernel) and ID (distro)
test -z "$OS" && OS="$(uname | tr '[:upper:]' '[:lower:]')"
case "$OS" in
linux)
  source /etc/os-release
  test "$ID" = "archarm" && ID="arch"
  ;;
darwin)
  ID="osx"
  test -z "$HOME" && HOME=/Users/$(whoami)
  ;;
Windows_NT|CYGWIN_NT-*)
  OS="windows"
  ID="cygwin"
  ;;
*)
  echo "Your platform '$(uname)' can not be identified." >/dev/stderr
esac

# Dotfiles
test -z "$DOTFILES" && export DOTFILES="$HOME/dotfiles" # default location
for f in $DOTFILES/shell/*.$(basename $SHELL) $DOTFILES/shell/*.sh $DOTFILES/shell/*.$ID $DOTFILES/shell/*.$OS; do
  source "$f" >/dev/null
done

# Display Files
cd
pwd
ls
