source dotfiles/shell/bashrc

# Enable arch partition access for VirtualBox
echo 7299 | sudo -S chmod 0777 /dev/disk0* 2>/dev/null

# Delete default home folders that recreate periodically (sourced from dotfiles/shell/tidyhome.osx)
tidy_home

# Bind mount other partitions
echo 7299 | sudo -S bindfs -o multithreaded /Volumes/shared/applications /Applications 2>/dev/null
mkdir -p Pictures
rm Pictures/* 2>/dev/null
cp $(lr .walls | tail) Pictures 2>/dev/null
