# Test for fd 0 (stdin), which implies interactive input
test -t 0 || return 1

# Shell functions
for file in $HOME/.config/${SHELL##*/}/{*.${SHELL##*/},*.sh,*.${ID:-arch},*.${OS:-linux}}; do
  source "$file" >/dev/null
done
