#!/bin/bash

herbstclient emit_hook reload # tell listeners reload (herbstclient --idle)

# Settings
source $HOME/.config/herbstluftwm/style.sh
source $HOME/.config/herbstluftwm/layouts.sh # must create tags before panel starts
source $HOME/.config/herbstluftwm/keybind.sh # must come after layouts creates tags

# Multi Monitor Setup
herbstclient detect_monitors #set_monitors 1280x1024+0+0 1280x1024+1280+0

# Panels
killall trayer
panel_height=15 # change for HiDPI monitors
panel="bash $HOME/.config/herbstluftwm/panel.sh" # Based on: /etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d':' -f1); do
  herbstclient spawn trayer --edge top --align right --widthtype request --heighttype pixel --height $panel_height --transparent true --alpha 255 --expand true --monitor $monitor
  herbstclient spawn $panel $monitor $panel_height
done

# Unlock (allow repaint)
herbstclient unlock
