source dotfiles/shell/bashrc

# Enable arch partition access for VirtualBox
echo 7299 | sudo -S chmod 0777 /dev/disk0* 2>/dev/null

# Delete default home folders that recreate periodically
tidy_home # sourced from dotfiles/shell/tidyhome.osx
