#!/bin/bash

herbstclient emit_hook reload # tell listeners reload (herbstclient --idle)


# Settings
source $HOME/.config/herbstluftwm/style.sh
source $HOME/.config/herbstluftwm/layout.sh
source $HOME/.config/herbstluftwm/keybind.sh


# Multi Monitor Setup
herbstclient detect_monitors #set_monitors 1280x1024+0+0 1280x1024+1280+0
# dual monitor setup
#hc remove monitor 1
#hc move_monitor 0 1366x768+0+0
#hc use "${TAG_NAMES[0]}"
#hc add_monitor 1440x900+1366+0 "${TAG_NAMES[1]}"


# Unlock (allow repaint)
herbstclient unlock
